//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Art_min
    {
        public string empresa { get; set; }
        public string co_art { get; set; }
        public decimal uni_min { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
