//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autori_Equipo
    {
        public int num_autori { get; set; }
        public int num_equipo { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public string descrip { get; set; }
        public string autorizado { get; set; }
        public bool anulado { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
