//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipos
    {
        public int num_equipo { get; set; }
        public string equi_des { get; set; }
        public string serial { get; set; }
        public System.DateTime fec_adq { get; set; }
        public System.DateTime fec_reg { get; set; }
        public decimal valor { get; set; }
        public string co_acti { get; set; }
        public string empresa { get; set; }
        public string co_usuario { get; set; }
        public bool activo { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
