//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gene_claves
    {
        public string clave { get; set; }
        public string co_usuario { get; set; }
        public string empresa { get; set; }
        public System.DateTime fec_venc { get; set; }
        public int cantidad { get; set; }
        public int cant_gene { get; set; }
        public int anulada { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime fec_us_in { get; set; }
    }
}
