//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Config_Logica
    {
        public string id_activo { get; set; }
        public string co_campo { get; set; }
        public string valor { get; set; }
        public System.Guid Rowguid { get; set; }
    
        public virtual GIT_Campos_Logicos GIT_Campos_Logicos { get; set; }
    }
}
