//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public string empresa { get; set; }
        public string co_art { get; set; }
        public string art_des { get; set; }
        public decimal prec_vta1 { get; set; }
        public decimal prec_vta2 { get; set; }
        public decimal prec_vta3 { get; set; }
        public decimal prec_vta4 { get; set; }
        public System.DateTime fec_emis { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
