//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Profit_RG_2K12Entities : DbContext
    {
        public Profit_RG_2K12Entities()
            : base("name=Profit_RG_2K12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<pSeleccionarDoc_ODCI_Result> pSeleccionarDoc_ODCI(string empresa, Nullable<int> num_doc)
        {
            var empresaParameter = empresa != null ?
                new ObjectParameter("Empresa", empresa) :
                new ObjectParameter("Empresa", typeof(string));
    
            var num_docParameter = num_doc.HasValue ?
                new ObjectParameter("Num_doc", num_doc) :
                new ObjectParameter("Num_doc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSeleccionarDoc_ODCI_Result>("pSeleccionarDoc_ODCI", empresaParameter, num_docParameter);
        }
    }
}
