//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autori_Equipo
    {
        public int num_autori { get; set; }
        public int num_equipo { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public string descrip { get; set; }
        public string autorizado { get; set; }
        public bool anulado { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
