//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embarque
    {
        public Embarque()
        {
            this.Reng_emb = new HashSet<Reng_emb>();
        }
    
        public int nro_viaje { get; set; }
        public string bl { get; set; }
        public System.DateTime fecha_sal { get; set; }
        public System.DateTime fecha_lleg { get; set; }
        public string co_consig { get; set; }
        public string des_consig { get; set; }
        public string pto_sal { get; set; }
        public string pto_lleg { get; set; }
        public string co_naviera { get; set; }
        public string co_shipper { get; set; }
        public string shipper_des { get; set; }
        public byte[] validador { get; set; }
        public int c20p { get; set; }
        public int c40p { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Naviera Naviera { get; set; }
        public virtual ICollection<Reng_emb> Reng_emb { get; set; }
    }
}
