//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_diaria
    {
        public System.DateTime fecha { get; set; }
        public int id_meta { get; set; }
        public string grupo { get; set; }
        public Nullable<decimal> porc { get; set; }
        public System.Guid rowguid { get; set; }
        public int id_num { get; set; }
        public decimal tasa_aju { get; set; }
        public decimal diaria_aju { get; set; }
    
        public virtual Metas_Vtas Metas_Vtas { get; set; }
    }
}
