//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gene_claves
    {
        public string clave { get; set; }
        public string co_usuario { get; set; }
        public string empresa { get; set; }
        public System.DateTime fec_venc { get; set; }
        public int cantidad { get; set; }
        public int cant_gene { get; set; }
        public int anulada { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime fec_us_in { get; set; }
    }
}
