//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Adquisicion
    {
        public string id_adquisicion { get; set; }
        public string id_consumible { get; set; }
        public decimal valor { get; set; }
        public string unidades { get; set; }
        public System.DateTime fecha { get; set; }
        public string co_ubic { get; set; }
        public string co_consultor { get; set; }
        public System.Guid Rowguid { get; set; }
    }
}
