//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Mantenimiento
    {
        public int id_mtto { get; set; }
        public string id_activo { get; set; }
        public System.DateTime fecha { get; set; }
        public string observacion { get; set; }
        public decimal valor { get; set; }
        public string asesor_ext { get; set; }
        public string co_consultor { get; set; }
        public string problema { get; set; }
        public string solucion { get; set; }
        public System.Guid Rowguid { get; set; }
    
        public virtual GIT_Consultor GIT_Consultor { get; set; }
    }
}
