//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Consultor
    {
        public GIT_Consultor()
        {
            this.GIT_Mantenimiento = new HashSet<GIT_Mantenimiento>();
        }
    
        public string co_consultor { get; set; }
        public string nombre { get; set; }
        public System.Guid Rowguid { get; set; }
    
        public virtual ICollection<GIT_Mantenimiento> GIT_Mantenimiento { get; set; }
    }
}
