//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Activo
    {
        public string id_activo { get; set; }
        public string descrip { get; set; }
        public string serial { get; set; }
        public string modelo { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fecha_reg { get; set; }
        public System.DateTime fecha_adq { get; set; }
        public Nullable<System.DateTime> fecha_reti { get; set; }
        public string co_ubic { get; set; }
        public int id_asign { get; set; }
        public string id_cat_activo { get; set; }
        public System.Guid Rowguid { get; set; }
    }
}
