//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ig_pedidos
    {
        public string empresa { get; set; }
        public string nomina { get; set; }
        public string cod_emp { get; set; }
        public string nombre_completo { get; set; }
        public System.DateTime fecha { get; set; }
        public int fact_num { get; set; }
        public System.DateTime f_ini { get; set; }
        public System.DateTime f_fin { get; set; }
        public string observa { get; set; }
        public bool anulado { get; set; }
        public System.Guid rowguid { get; set; }
        public System.Guid rowgpedido { get; set; }
    }
}
