//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metas_Vtas
    {
        public Metas_Vtas()
        {
            this.Est_diaria = new HashSet<Est_diaria>();
        }
    
        public int id_meta { get; set; }
        public string grupo { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public System.Guid rowguid { get; set; }
        public decimal meta { get; set; }
        public decimal tasa { get; set; }
    
        public virtual ICollection<Est_diaria> Est_diaria { get; set; }
    }
}
