//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisado
    {
        public int sup_num { get; set; }
        public string nomina { get; set; }
        public string cod_emp { get; set; }
        public string co_usuario { get; set; }
        public string nombre { get; set; }
        public System.Guid Rowguid { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
