//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excepcion_P
    {
        public string empresa { get; set; }
        public string cod_emp { get; set; }
        public string nombre_completo { get; set; }
        public bool status { get; set; }
        public System.DateTime fecha { get; set; }
        public string motivo { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime fe_us_in { get; set; }
    }
}
