//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Ubicaciones
    {
        public string co_ubic { get; set; }
        public string descrip { get; set; }
        public System.Guid Rowguid { get; set; }
    }
}
