//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIT_Campos_Logicos
    {
        public GIT_Campos_Logicos()
        {
            this.GIT_Config_Logica = new HashSet<GIT_Config_Logica>();
        }
    
        public string co_campo { get; set; }
        public string descrip { get; set; }
        public System.Guid Rowguid { get; set; }
    
        public virtual ICollection<GIT_Config_Logica> GIT_Config_Logica { get; set; }
    }
}
