//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ig_reclamo_ped
    {
        public string empresa { get; set; }
        public int fact_num { get; set; }
        public string observa { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual Ig_reclamo_ped Ig_reclamo_ped1 { get; set; }
        public virtual Ig_reclamo_ped Ig_reclamo_ped2 { get; set; }
    }
}
