//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metas_Vtas
    {
        public Metas_Vtas()
        {
            this.Est_diaria = new HashSet<Est_diaria>();
        }
    
        public int id_meta { get; set; }
        public string grupo { get; set; }
        public System.DateTime desde { get; set; }
        public System.DateTime hasta { get; set; }
        public System.Guid rowguid { get; set; }
        public decimal meta { get; set; }
        public decimal tasa { get; set; }
    
        public virtual ICollection<Est_diaria> Est_diaria { get; set; }
    }
}
