//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfitContenedor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public Reporte()
        {
            this.Filtros = new HashSet<Filtro>();
        }
    
        public string cod_rep { get; set; }
        public string titulo { get; set; }
        public string ruta { get; set; }
        public string Archivo { get; set; }
        public string funcion { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ICollection<Filtro> Filtros { get; set; }
    }
}
